Login: #登录模块
  login: #登录接口
    path: /account/sLogin
    method: POST
  logout:
    path:
    method: POST
Shop:
  query:
    path: /shopping/myShop
    method: GET
  update:
    path: /shopping/updatemyshop
    method: POST
  file_upload:
    path: /file
    method: POST
Food:
  food_less:
    path: /shopping/addcategory
    method: GET